export const GOODS_SET_IS_FETCHING = 'GOODS:SET_IS_FETCHING';
export const GOODS_SET_ITEMS = 'GOODS:SET_ITEMS';
export const GOODS_SET_CURRENT = 'GOODS:SET_CURRENT';
export const GOODS_ADD_ITEMS = 'GOODS:ADD_ITEMS';